name: Calier test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: Position

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'Admin'
          clientPrivateKey:
            path: '../Network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../Network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem'
    connectionProfile:
      path: '../Network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true